---
driver:
  name: vagrant
  network: 
  - ["forwarded_port", {guest: 3000, host: 3000}]

provisioner:
  name: chef_zero
  roles_path: '../../roles'

  
# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - role[flix_roles]
#      - recipe[deploy_flix::default]
    attributes:
